---
title: "psy 8712- week 12"
author: "Lisette Horne"
date: "2024-04-18"
output: html_document
---
#Script Settings and Resources
```{r setup, include=FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
library(tidytext)
library(wordcloud)
library(topicmodels)
library(tm)
library(RedditExtractoR)
library(ldatuning)
library(dendextend)
library(qdap)
library(textstem)
library(RWeka)

```

#Data Import
```{r}
#reddit_thread_urls <- find_thread_urls(
  #subreddit = "IOPsychology",
  #sort_by = "new",
  #period = "year") %>%
  #mutate(date_utc = ymd(date_utc))

#thread_urls2 <- filter(reddit_thread_urls, timestamp > as.numeric(as.POSIXct(Sys.Date() - 365)))

#reddit_urls <- reddit_thread_urls$url

#reddit_content <- get_thread_content(reddit_urls)

#week12_tbl <- tibble(
  #title = reddit_content$threads$title,
  #upvotes = reddit_content$threads$upvotes)

#write out all files as csv
#write_csv(reddit_thread_urls, file = "../data/reddit_data.csv")
#write_csv(week12_tbl, "../data/week12_tbl.csv")
reddit_thread_urls <- read_csv("../data/reddit_data.csv", show_col_types = FALSE)
week12_tbl <- read_csv("../data/week12_tbl.csv", show_col_types = FALSE)
```

```{r}
io_corpus_original <- VCorpus(VectorSource(week12_tbl$title))

io_corpus <- io_corpus_original %>%
  tm_map(content_transformer(replace_abbreviation)) %>%
  tm_map(content_transformer(replace_contraction)) %>%
  tm_map(content_transformer(str_to_lower)) %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>% 
  tm_map(removeWords, c("io psychology", "iopsy", "iopsych", "io psych", "iopsychology", "riopsychology", "organizational psychology", "industrial organizational psychology", "io", "i/o")) %>%
  tm_map(stripWhitespace) 
```

```{r}
compare_them <- function(x,y) {
  i <- sample.int(length(x), 1)
  print(x$content[[i]]$content)
  print(y$content[[i]]$content)
}

compare_them(io_corpus_original, io_corpus)
```

```{r}
tokenizer <- function(x) NGramTokenizer(x, Weka_control(min=1, max=2))

io_dtm <-  DocumentTermMatrix(io_corpus, control = list(tokenize = tokenizer))

io_slim_dtm <- removeSparseTerms(io_dtm, 0.997)
```




#Visualization

#Analysis


